<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>KRS.BetterJobs</AssemblyName>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>CS8600;CS8602;CS8603</WarningsAsErrors>
	</PropertyGroup>

	<!-- Derail Valley -->

	<!-- Unity -->

	<!-- Mod Loader -->
	<ItemGroup>
		<PackageReference Include="dnlib" Version="4.4.0" />
		<PackageReference Include="Lib.Harmony" Version="2.3.5" />
		<PackageReference Include="UnityModManager" Version="0.31.1" />
	</ItemGroup>

	<!-- Null Checking -->
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>I:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="DV.Common">
	    <HintPath>I:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\DV.Common.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>I:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>I:\SteamLibrary\steamapps\common\Derail Valley\DerailValley_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- Copy to build folder -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="../build/" />

		<!-- Package after Release build -->
		<Exec Command="powershell -ExecutionPolicy ByPass -Command &quot;(../package.ps1)&quot;" />
	</Target>
</Project>
